=== ppazos/hapi-testpanel/hunit/hunit-impl/src/main/resources/hunit_tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd" 
    xmlns:tns="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd" elementFormDefault="qualified">
	
	<element name="battery" type="tns:TestBattery"/>

    <simpleType name="requiredString">
        <restriction base="string">
            <pattern value=".+"></pattern>
        </restriction>
    </simpleType>
	
	<complexType name="TestBattery">
		<sequence>
            <element name="name" type="tns:requiredString" minOccurs="1" maxOccurs="1"/>
            <element name="notes" type="string" minOccurs="0" maxOccurs="1"/>
            
			<element name="interfaces" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="interface" type="tns:AnyInterface" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="tests" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="test" type="tns:Test" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
            <element name="messages" minOccurs="1" maxOccurs="1" type="tns:AnyMessageDefinitions">
            </element>
			
		</sequence>
		<attribute name="hunit_version" type="string"/>
	</complexType>
	
	<complexType name="AnyInterface">
		<choice>
			<element name="mllpHl7V2Interface" type="tns:MllpHl7V2Interface"/>
			<element name="jmsInterface" type="tns:JmsInterface"/>
			<element name="javaCallableInterface" type="tns:JavaCallableInterface"/>
		</choice>
	</complexType>
	
	<complexType name="Interface" abstract="true">
		<sequence>
			<element name="clear" type="boolean" minOccurs="0" default="true">
				<annotation>
					<documentation>
						If true, specifies the that hUnit
						should listen on this interface for messages to ignore
						when the interface starts before continuing. This is
						useful for instance if there is a chance old stale messages
						may be waiting on a given interface, and you want to allow
						them to be processed before beginning your unit testing.
					</documentation>
				</annotation>
			</element>
			<element name="clearMillis" type="int" minOccurs="0" default="100">
				<annotation>
					<documentation>
						If present, specifies the number of milliseconds hUnit
						should listen on this interface for messages to ignore
						when the interface starts before continuing. This is
						useful for instance if there is a chance old stale messages
						may be waiting on a given interface, and you want to allow
						them to be processed before beginning your unit testing.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="autostart" type="boolean"/>
		<attribute name="id" type="string" use="required"/>
	</complexType>

	<complexType name="MllpHl7V2Interface">
		<complexContent>
			<extension base="tns:Interface">
				<sequence>
					<element name="ip" type="string"/>
					<element name="port" type="int"/>
                    <element name="connectionTimeoutMillis" type="int" minOccurs="0"/>
                    <element name="mode" minOccurs="1" maxOccurs="1">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="client"></enumeration>
                                <enumeration value="server"></enumeration>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="encoding" type="tns:Hl7V2EncodingTypeEnum" minOccurs="0" maxOccurs="1" default="ER7">
                    </element>
                    <element name="autoAck" type="boolean" minOccurs="0" default="true"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Hl7V2EncodingTypeEnum">
		<restriction base="string">
			<enumeration value="ER7"></enumeration>
			<enumeration value="XML"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="MesssageTypeEnum">
		<restriction base="string">
			<enumeration value="HL7v2"></enumeration>
			<enumeration value="XML"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="JavaCallableInterface">
		<complexContent>
			<extension base="tns:Interface">
				<sequence>
					<element name="class" type="string"/>
					<element name="messageType" type="tns:MesssageTypeEnum"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="AbstractJmsInterface" abstract="true">
		<complexContent>
			<extension base="tns:Interface">
				<sequence>
					<element name="connection_factory" type="string"></element>
					<element name="connection_factory_constructor_arg" type="tns:JavaArgument" minOccurs="0" maxOccurs="unbounded"></element>
					<choice>
						<element name="queue_name" type="string"></element>
						<element name="topic_name" type="string"></element>
					</choice>
					<element name="user_name" type="string"></element>
					<element name="password" type="string"></element>
					<element name="message_property" type="tns:NamedJavaArgument" minOccurs="0" maxOccurs="unbounded"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="JmsInterface">
		<complexContent>
			<extension base="tns:AbstractJmsInterface">
				<sequence>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Test">
        <sequence>
			<element name="name" type="tns:requiredString" minOccurs="1" maxOccurs="1"></element>
			<choice minOccurs="1" maxOccurs="unbounded">
				<element name="send_message" type="tns:SendMessageAny"/>
				<element name="expect_message" type="tns:ExpectMessageAny"/>
				<element name="expect_no_message" type="tns:ExpectNoMessage"/>
			</choice>
        </sequence>
	</complexType>
	
	<complexType name="SendMessageAny">
		<choice minOccurs="1" maxOccurs="1">
			<element name="hl7v2" minOccurs="1" maxOccurs="1" type="tns:Hl7V2SendMessage"/>
			<element name="xml" minOccurs="1" maxOccurs="1" type="tns:XMLSendMessage"/>
		</choice>
	</complexType>

    <complexType name="Event" abstract="true">
        <attribute name="interface_id" type="string" use="required"></attribute>
    </complexType>

    <complexType name="SendMessage">
        <complexContent>
            <extension base="tns:Event">
		        <attribute name="message_id" type="string" use="optional"></attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Hl7V2SendMessage">
        <complexContent>
            <extension base="tns:SendMessage">
				<sequence>
                    <element name="message" minOccurs="1" maxOccurs="1" type="tns:Hl7V2MessageDefinition"/>
                    <element name="encoding" minOccurs="0" maxOccurs="1" default="ER7">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="ER7"></enumeration>
                                <enumeration value="XML"></enumeration>
                            </restriction>
                        </simpleType>
                    </element>
				</sequence>
			</extension>
        </complexContent>
    </complexType>

    <complexType name="ExpectEvent" abstract="true">
        <complexContent>
            <extension base="tns:Event">
            	<sequence>
            	</sequence>
                <attribute name="receive_timeout_millis" type="long" use="optional"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ExpectMessage" abstract="true">
        <complexContent>
            <extension base="tns:ExpectEvent">
            	<sequence>
            	</sequence>
                <attribute name="message_id" type="string" use="optional"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ExpectNoMessage">
        <complexContent>
            <extension base="tns:ExpectEvent">
            	<sequence>
            	</sequence>
            </extension>
        </complexContent>
    </complexType>

	<complexType name="ExpectMessageAny">
		<choice minOccurs="1" maxOccurs="1">
			<element name="hl7v2_specific" minOccurs="1" maxOccurs="1" type="tns:Hl7V2ExpectSpecificMessage"/>
            <element name="hl7v2_ack" minOccurs="1" maxOccurs="1" type="tns:Hl7V2ExpectAck"/>
            <element name="hl7v2_nak" minOccurs="1" maxOccurs="1" type="tns:Hl7V2ExpectNak"/>
            <element name="hl7v2_rules" minOccurs="1" maxOccurs="1" type="tns:Hl7V2ExpectRules"/>
			<element name="xml_specific" minOccurs="1" maxOccurs="1" type="tns:XMLExpectSpecificMessage"/>
		</choice>
	</complexType>
	
	<complexType name="XMLSendMessage">
        <complexContent>
            <extension base="tns:SendMessage">
                <sequence>
                    <element name="message" minOccurs="1" maxOccurs="1" type="tns:XmlMessageDefinition"/>
                </sequence>
            </extension>
        </complexContent>
	</complexType>

    <complexType name="MessageSource">
        <choice>
            <element name="ref" type="string" minOccurs="1" maxOccurs="1"></element>
        </choice>
    </complexType>

    <complexType name="HL7V2ExpectAbstract" abstract="true">
        <complexContent>
            <extension base="tns:ExpectMessage">
                <sequence>
					<element name="reply_message" type="string" minOccurs="0" maxOccurs="1">
					</element>
                    <element name="reply_msg" type="tns:Hl7V2MessageDefinition" minOccurs="0" maxOccurs="1">
                    </element>
                </sequence>                    
            </extension>
        </complexContent>
    </complexType>

	<complexType name="Hl7V2ExpectSpecificMessage">
        <complexContent>
            <extension base="tns:HL7V2ExpectAbstract">
                <sequence>
                    <element name="message" minOccurs="1" maxOccurs="1" type="tns:Hl7V2MessageDefinition"/>
                </sequence>
            </extension>
        </complexContent>
	</complexType>

    <complexType name="Hl7V2ExpectAck">
        <complexContent>
            <extension base="tns:Hl7V2ExpectRules">
                <sequence>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Hl7V2ExpectNak">
        <complexContent>
            <extension base="tns:Hl7V2ExpectRules">
                <sequence>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Hl7V2ExpectRules">
        <complexContent>
            <extension base="tns:HL7V2ExpectAbstract">
                <sequence>
                    <element name="rule" type="tns:TerserMessageRule" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TerserMessageRule">
        <sequence>
            <element name="path" type="tns:requiredString"/>
            <element name="value" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="pattern" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="notValue" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="notPattern" type="string" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

	<complexType name="XMLExpectMessage">
        <complexContent>
            <extension base="tns:ExpectMessage">
				<sequence>
					<element name="validateMessageUsingDTD" type="boolean" minOccurs="0" maxOccurs="1" default="false"/>
				</sequence>
            </extension>
        </complexContent>
	</complexType>

	<complexType name="XMLExpectSpecificMessage">
		<complexContent>
			<extension base="tns:XMLExpectMessage">
				<sequence>
                    <element name="message" minOccurs="1" maxOccurs="1" type="tns:XmlMessageDefinition"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="AckMessage">
	</complexType>

    <complexType name="NakMessage">
    </complexType>

    <complexType name="AnyMessageDefinitions">
        <sequence>
	        <choice minOccurs="0" maxOccurs="unbounded">
	            <element name="hl7v2" type="tns:Hl7V2MessageDefinition"></element>
	            <element name="xml" type="tns:XmlMessageDefinition"></element>
	        </choice>
        </sequence>
    </complexType>

    <complexType name="MessageDefinition">
		<choice>
		    <element name="text" type="string"></element>
		</choice>
        <attribute name="id" type="string" use="required"/>
    </complexType>
	
	<complexType name="Hl7V2MessageDefinition">
	   <complexContent>
	       <extension base="tns:MessageDefinition">
	       </extension>
	   </complexContent>
	</complexType>

	<complexType name="XmlMessageDefinition">
	   <complexContent>
	       <extension base="tns:MessageDefinition">
	       </extension>
	   </complexContent>
	</complexType>

	<complexType name="JavaArgument">
		<attribute name="type" type="string"></attribute>
		<attribute name="value" type="string"></attribute>
	</complexType>

	<complexType name="NamedJavaArgument">
		<complexContent>
			<extension base="tns:JavaArgument">
				<attribute name="name" type="string"></attribute>
			</extension>
		</complexContent>
	</complexType>
	
</schema>

=== ppazos/hapi-testpanel/hunit/src/site/resources/examples/sample_jms.xml
<?xml version="1.0" encoding="UTF-8"?>
<hu:battery xmlns:hu="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd http://hl7api.sourceforge.net/hunit/hunit_tests.xsd">

	<hu:name>ORM_WCH_ccRIS to SIU_WCH_Kiosk</hu:name>
        
	<hu:interfaces>
		<hu:interface>
			<hu:jmsInterface id="from_ORM_WCH_ccRIS">
				<hu:connection_factory>com.stc.jms.client.STCTopicConnectionFactory</hu:connection_factory>
				<hu:connection_factory_constructor_arg type="java.lang.String" value="jcapsdev"/>
				<hu:connection_factory_constructor_arg type="int" value="18907"/>
				<hu:topic_name>tp_In_ORM_WCH_ccRIS</hu:topic_name>
				<hu:user_name>Administrator</hu:user_name>
				<hu:password>PASSWORD</hu:password>
				<hu:message_property type="java.lang.String" name="SOURCE_SYSTEM" value="WCH_ccRIS"/>
				<hu:message_property type="java.lang.String" name="SOURCE_INTERFACE" value="ORM"/>
			</hu:jmsInterface>
		</hu:interface>
		<hu:interface>
			<hu:jmsInterface id="to_SIU_WCH_Kiosk">
				<hu:connection_factory>com.stc.jms.client.STCQueueConnectionFactory</hu:connection_factory>
				<hu:connection_factory_constructor_arg type="java.lang.String" value="jcapsdev"/>
				<hu:connection_factory_constructor_arg type="int" value="18907"/>
				<hu:queue_name>q_Out_ADTSIU_WCH_Kiosk</hu:queue_name>
				<hu:user_name>Administrator</hu:user_name>
				<hu:password>PASSWORD</hu:password>
			</hu:jmsInterface>
		</hu:interface>			
	</hu:interfaces>
	<hu:tests>
		<hu:test>
			<hu:name>Regular Order</hu:name>
			<hu:send_message>
				<hu:hl7v2 interface_id="from_ORM_WCH_ccRIS" message_id="Normal Order In" />
			</hu:send_message>
			<hu:expect_message>
                <hu:hl7v2_specific interface_id="to_SIU_WCH_Kiosk" message_id="Normal Order Out"/>
			</hu:expect_message>
		</hu:test>
	</hu:tests>
	<hu:messages>
		<hu:hl7v2 id="Normal Order In">
			<hu:text><![CDATA[
MSH|^~\&|WCH_ccRIS|WCH|||200905131421||OMI^O23^OMI_O23|359|T|2.5
PID|||7009511^^^Sunnybrook^MR^^~01010101010^^^CANON^JHN^^||Test^Rbc^Clinic||19800717|F|||20 bay st^^TORONTO^ON^M5G 2N7^Can^H||(416)235-6897^PRN^PH
PV1|1|O||||||47251^Smith^Arnold I.^^^Dr^MD|47251^Smith^Arnold I.^^^Dr^MD||||||||||10940000227^^^Sunnybrook^VN||||||||||||||||||||||||||||||||
ORC|NW|123999^ccRIS|||SC|||||||140857^Ward^Richard^^^Dr.^MD^^2.16.840.1.113883.3.59.3:862^L^^^EI|||||||||||||||||
TQ1|1||||||200907171200|200907171230|
OBR||123999||0302005^CT Abdomen|||200907171200|200907171230||||||||140857^Ward^Richard^^^Dr.^MD^^2.16.840.1.113883.3.59.3:862^L^^^EI||||||||||||||||||||||||||||||
		]]></hu:text>
		</hu:hl7v2>
		<hu:hl7v2 id="Normal Order Out">
			<hu:text><![CDATA[
MSH|^~\&|WCH_ccRIS|WCH|||200905131421||SIU^S12^SIU_S12|359|T|2.5
SCH||123999^WCH_ccRIS||||S12^^HS
PID|||7009511^^^Sunnybrook^MR^^~01010101010^^^CANON^JHN^^||Test^Rbc^Clinic||19800717|F|||20 bay st^^TORONTO^ON^M5G 2N7^Can^H||(416)235-6897^PRN^PH
PV1|1|O||||||47251^Smith^Arnold I.^^^Dr^MD|47251^Smith^Arnold I.^^^Dr^MD||||||||||123999^^^WCH_ccRIS^VN|||||||||||||||||||||||||||||||
RGS|1||
AIS|1||MI_CT^CT Abdomen|200907171200|0|MIN^MINUTES^ISO|30|MIN^MINUTES^ISO||BOOKED^BOOKED^HL70278||		]]></hu:text>
		</hu:hl7v2>
	</hu:messages>
</hu:battery>

=== ppazos/hapi-testpanel/hunit/hunit-impl/src/main/resources/ca/uhn/hunit/templates/hl7_in_and_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
The base tag for hUnit is a battery. A Battery defines one or more tests. 
-->
<hu:battery xmlns:hu="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd http://hl7api.sourceforge.net/hunit/hunit_tests.xsd">

    <!--
    First, the battery is given a name 
    -->	
	<hu:name>TestBattery</hu:name>
	
	<!-- 
	Then, any interfaces needed by the test are defined
	-->
	<hu:interfaces>
		
		<!--
		This test has two interfaces, both of which are TCP MLLP interfaces for
		HL7 v2. One is a server socket which will receive messages with an ID of
		"test_in_interface". One is a client interface which will send messages
		with an ID of "test_out_interface".
		-->
		<hu:interface>
			<hu:mllpHl7V2Interface id="ReceiveInterface" autostart="false">
				<hu:ip>localhost</hu:ip>
				<hu:port>10200</hu:port>
				<hu:mode>server</hu:mode>
				<hu:clear>false</hu:clear>
			</hu:mllpHl7V2Interface>
		</hu:interface>
		<hu:interface>
			<hu:mllpHl7V2Interface id="SendInterface" autostart="false">
				<hu:ip>localhost</hu:ip>
				<hu:port>10201</hu:port>
				<hu:mode>client</hu:mode>
			</hu:mllpHl7V2Interface>
		</hu:interface>
		
	</hu:interfaces>
	
	<!--
	Next, we define some tests
	-->
	<hu:tests>
	
        <!-- 
        This test sends a message to the interface "test_out_interface". The message
        is defined below. It has the ID "SendMessage".
        
        The test then expects to receive a message on the interface "test_in_interface".
        The expected message should match exactly the contents of the message defined
        below with the ID "NormalReceiveMessage".
        -->
		<hu:test>
			<hu:name>Test 1</hu:name>
			<hu:send_message>
				<hu:hl7v2 interface_id="SendInterface" message_id="SendMessage" />
			</hu:send_message>
			<hu:expect_message>
                <hu:hl7v2_specific interface_id="ReceiveInterface" message_id="ReceiveMessage"/>
			</hu:expect_message>
		</hu:test>
		
	</hu:tests>
	
	<!-- 
	Finally, we define the messages used
	-->
	<hu:messages>
		<hu:hl7v2 id="SendMessage">
			<hu:text><![CDATA[
MSH|^~\&|ULTRA|TML|OLIS|OLIS|200905011130||ORU^R01|20169838|T|2.3
PID|||7005728^^^TML^MR||LEIGHTON^RACHEL^DIAMOND||19310313|F|||200 ANYWHERE ST^^TORONTO^ON^M6G 2T9||(416)888-8888||||||1014071185^KR
PV1|1||OLIS||||OLIST^BLAKE^DONALD^THOR^^^^^921379^^^^OLIST
ORC|RE||T09-100442-RET-0^^OLIS_Site_ID^ISO|||||||||OLIST^BLAKE^DONALD^THOR^^^^L^921379
OBR|0||T09-100442-RET-0^^OLIS_Site_ID^ISO|RET^RETICULOCYTE COUNT^HL79901 literal|||200905011106|||||||200905011106||OLIST^BLAKE^DONALD^THOR^^^^L^921379||7870279|7870279|T09-100442|MOHLTC|200905011130||B7|F||1^^^200905011106^^R
OBX|1|NM|Z114099^Erc^L||4.00|tril/L|3.90-5.60||||F|||200905011111|PMH
           ]]></hu:text>
		</hu:hl7v2>
		<hu:hl7v2 id="ReceiveMessage">
			<hu:text><![CDATA[
MSH|^~\&|ULTRA|TML|OLIS|OLIS|200905011130||ORU^R01|20169838|T|2.3
PID|||7005728^^^TML^MR||TEST^RACHEL^DIAMOND||19310313|F|||200 ANYWHERE ST^^TORONTO^ON^M6G 2T9||(416)888-8888||||||1014071185^KR
PV1|1||OLIS||||OLIST^BLAKE^DONALD^THOR^^^^^921379^^^^OLIST
ORC|RE||T09-100442-RET-0^^OLIS_Site_ID^ISO|||||||||OLIST^BLAKE^DONALD^THOR^^^^L^921379
OBR|0||T09-100442-RET-0^^OLIS_Site_ID^ISO|RET^RETICULOCYTE COUNT^HL79901 literal|||200905011106|||||||200905011106||OLIST^BLAKE^DONALD^THOR^^^^L^921379||7870279|7870279|T09-100442|MOHLTC|200905011130||B7|F||1^^^200905011106^^R
OBX|1|NM|Z114099^Erc^L||4.00|tril/L|3.90-5.60||||F|||200905011111|PMH
           ]]></hu:text>
		</hu:hl7v2>
	</hu:messages>
</hu:battery>

=== ppazos/hapi-testpanel/hunit/hunit-impl/src/test/resources/unit_tests_jms.xml
<?xml version="1.0" encoding="UTF-8"?>
<hu:battery xmlns:hu="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://hl7api.sourceforge.net/hunit/hunit_tests.xsd http://hl7api.sourceforge.net/hunit/hunit_tests.xsd">
	<hu:name>TestBattery</hu:name>
	<hu:interfaces>
		<hu:interface>
			<hu:jmsInterface id="test_in_interface">
				<hu:connection_factory>ca.uhn.hunit.iface.StaticActiveMQConnectionFactory</hu:connection_factory>
				<hu:connection_factory_constructor_arg type="java.lang.String" value="string value"></hu:connection_factory_constructor_arg>
				<hu:connection_factory_constructor_arg type="java.lang.Integer" value="1234"></hu:connection_factory_constructor_arg>
				<hu:queue_name>test_queue</hu:queue_name>
				<hu:user_name>user</hu:user_name>
				<hu:password>pass</hu:password>
			</hu:jmsInterface>
		</hu:interface>
		<hu:interface>
			<hu:jmsInterface id="test_out_interface">
				<hu:connection_factory>ca.uhn.hunit.iface.StaticActiveMQConnectionFactory</hu:connection_factory>
				<hu:queue_name>test_queue</hu:queue_name>
				<hu:user_name>user</hu:user_name>
				<hu:password>pass</hu:password>
			</hu:jmsInterface>
		</hu:interface>
	</hu:interfaces>
	<hu:tests>
		<hu:test>
			<hu:name>ExpectSameMessage</hu:name>
			<hu:send_message>
				<hu:hl7v2 interface_id="test_out_interface" message_id="InputMessage" />
			</hu:send_message>
			<hu:expect_message>
                <hu:hl7v2_specific interface_id="test_in_interface" message_id="InputMessage"/>
			</hu:expect_message>
		</hu:test>
        <hu:test>
            <hu:name>ExpectDifferentMessage</hu:name>
            <hu:send_message>
                <hu:hl7v2 interface_id="test_out_interface" message_id="InputMessage" />
            </hu:send_message>
            <hu:expect_message>
                <hu:hl7v2_specific interface_id="test_in_interface" message_id="DifferentOutputMessage"/>
            </hu:expect_message>
        </hu:test>
	</hu:tests>
	<hu:messages>
		<hu:hl7v2 id="InputMessage">
			<hu:text><![CDATA[
MSH|^~\&|ULTRA|TML|OLIS|OLIS|200905011130||ORU^R01|20169838|T|2.3
PID|||7005728^^^TML^MR||LEIGHTON^RACHEL^DIAMOND||19310313|F|||200 ANYWHERE ST^^TORONTO^ON^M6G 2T9||(416)888-8888||||||1014071185^KR
PV1|1||OLIS||||OLIST^BLAKE^DONALD^THOR^^^^^921379^^^^OLIST
ORC|RE||T09-100442-RET-0^^OLIS_Site_ID^ISO|||||||||OLIST^BLAKE^DONALD^THOR^^^^L^921379
OBR|0||T09-100442-RET-0^^OLIS_Site_ID^ISO|RET^RETICULOCYTE COUNT^HL79901 literal|||200905011106|||||||200905011106||OLIST^BLAKE^DONALD^THOR^^^^L^921379||7870279|7870279|T09-100442|MOHLTC|200905011130||B7|F||1^^^200905011106^^R
OBX|1|NM|Z114099^Erc^L||4.00|tril/L|3.90-5.60||||F|||200905011111|PMH
           ]]></hu:text>
		</hu:hl7v2>
        <hu:hl7v2 id="DifferentOutputMessage">
            <hu:text><![CDATA[
MSH|^~\&|ULTRA|TML|OLIS|OLIS|200905011130||ORU^R01|20169838|T|2.3
PID|||7005728^^^TML^MR||TEST2^RACHEL^DIAMOND||19310313|F|||200 ANYWHERE ST^^TORONTO^ON^M6G 2T9||(416)888-8888||||||1014071185^KR
PV1|1||OLIS||||OLIST^BLAKE^DONALD^THOR^^^^^921379^^^^OLIST
ORC|RE||T09-100442-RET-0^^OLIS_Site_ID^ISO|||||||||OLIST^BLAKE^DONALD^THOR^^^^L^921379
OBR|0||T09-100442-RET-0^^OLIS_Site_ID^ISO|RET^RETICULOCYTE COUNT^HL79901 literal|||200905011106|||||||200905011106||OLIST^BLAKE^DONALD^THOR^^^^L^921379||7870279|7870279|T09-100442|MOHLTC|200905011130||B7|F||1^^^200905011106^^R
OBX|1|NM|Z114099^Erc^L||4.00|tril/L|3.90-5.60||||F|||200905011111|PMH
           ]]></hu:text>
        </hu:hl7v2>
	</hu:messages>
</hu:battery>
